### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by biplab-sutradhar** [Logging-Stuff/RetroUI#17]
facing issue to set up the repo when try run this project then show that
 pnpm dev

> retro-ui@0.1.0 devv
> next dev

node:internal/process/promises:289
triggerUncaughtException(err, true /* fromPromise */);
^

Error: Cannot find package ' \repo\retroui\node_modules\.pnpm\@effect-ts+otel-exporter-trace-otlp-grpc@0.15.1_@effect-ts+core@0.60.5_@opentelemetry+api@1.9_3yh6i73ktoiclezpwntnqnmmte\node_modules\@opentelemetry\exporter-trace-otlp-grpc\package.json' imported from \repo\retroui\node_modules\.pnpm\@effect-ts+otel-exporter-trace-otlp-grpc@0.15.1_@effect-ts+core@0.60.5_@opentelemetry+api@1.9_3yh6i73ktoiclezpwntnqnmmte\node_modules\@effect-ts\otel-exporter-trace-otlp-grpc\_mjs\index.mjs
Did you mean to import @opentelemetry+exporter-trace-otlp-grpc@0.39.1_@opentelemetry+api@1.9.0/node_modules/@opentelemetry/exporter-trace-otlp-grpc/build/src/index.js?
at legacyMainResolve (node:internal/modules/esm/resolve:214:26)
at packageResolve (node:internal/modules/esm/resolve:840:14)
at moduleResolve (node:internal/modules/esm/resolve:910:20)
at defaultResolve (node:internal/modules/esm/resolve:1130:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:396:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:365:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:38)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
at link (node:internal/modules/esm/module_job:84:36) {
code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.11.0
 ELIFECYCLE  Command failed with exit code 1.
 
 
 although I installed using pnpm
 
 pnpm i
Lockfile is up to date, resolution step is skipped
Packages: +662
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 662, reused 662, downloaded 0, added 662, done
node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild: Running postinstall script, done in 887ms
node_modules/.pnpm/contentlayer@0.3.4_esbuild@0.18.20/node_modules/contentlayer: Running postinstall script, done in 1.4s

dependencies:
+ @headlessui/react 2.1.9
+ @radix-ui/react-avatar 1.1.1
+ class-variance-authority 0.7.0
+ clsx 2.1.1
+ contentlayer 0.3.4
+ date-fns 4.1.0
+ lucide-react 0.445.0
+ next 14.2.7
+ next-contentlayer 0.3.4
+ react 18.0.0
+ react-dom 18.0.0
+ rehype-pretty-code 0.14.0
+ rehype-slug 6.0.0
+ tailwind-merge 2.5.3
+ unist-builder 4.0.0
+ unist-util-visit 5.0.0

devDependencies:
+ @types/node 20.0.0
+ @types/react 18.0.0
+ @types/react-dom 18.0.0
+ eslint 8.0.0
+ eslint-config-next 14.2.7
+ postcss 8.0.0
+ tailwindcss 3.4.1
+ typescript 5.0.2

Done in 24.6s
 
 
  can you please help issue facing

**Comment by ariflogs** [comment]
unfortunately I couldn't recreate your scenario.. I cloned the project in a new folder but it was working fine for me. 
Can you delete the project and create a new? if that doesn't solve it, please shoot me a DM on discord and we can get in a call to resolve this.

**Comment by biplab-sutradhar** [comment]
I tried three times. Maybe I will ask in discord thanks for your time.
