### ISSUE TITLE
sidebar responsiveness fix

### ISSUE THREAD

**Issue by biplab-sutradhar** [Logging-Stuff/RetroUI#21]
before:
![image](https://github.com/user-attachments/assets/eae1df08-5072-41ac-b43a-1743e8dc1040)
![image](https://github.com/user-attachments/assets/1a82ec36-0f6e-4fcb-8af7-aed855bc1272)
after:
![image](https://github.com/user-attachments/assets/677ba2d1-b149-47e6-ae2b-0f6fe87e5cf2)
![image](https://github.com/user-attachments/assets/b51ab4cd-cecc-467d-94a2-703b2e682b10)
@ariflogs is there anything to do more or need to add

**Comment by ariflogs** [comment]
No need to change the desktop screen. (I might add some padding later for the tablet/ipad screen)
On phone screen, the navbar should be at the same place as the desktop navbar. 👇
<img width="355" alt="Screenshot 2024-10-19 at 10 23 23" src="https://github.com/user-attachments/assets/ea421eda-d7a1-4e90-9977-2d705bad3f68">
